-- 내부 조인(INNER JOIN): INNER 생략가능
select * from EMPBASICS_T A
INNER JOIN EMPFAMILY_T B
ON A.BMPCD = B.EMPCD;

SELECT * FROM FAMILYINFO_T A
JOIN EMPFAMILY_T B
ON A.RELACD = B.RELACD;

--내츄럴 조인(NATURAL JOIN)
SELECT * FROM EMP E 
NATURAL JOIN DEPT D;

SELECT * FROM FAMILYINFO_T A 
NATURAL JOIN EMPFAMILY_T B;
-- 네츄럴 조인 - USING절
-- 방법1
SELECT * FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMPTAX_T A
JOIN EMPANNUALHISTORY_T B
ON A.YEAR = B.YEAR;

-- 방법2
SELECT * FROM EMP INNER JOIN DEPT
USING(DEPTNO);

SELECT * FROM EMPTAX_T A 
JOIN EMPANNUALHISTORY_T B
USING (YEAR);

-- 외부조인(OUTER JOIN)
--LEFT OUTER JOIN
SELECT * FROM STADIUM 
LEFT OUTER JOIN TEAM
ON HOMETEAM_ID = TEAM_ID;

SELECT * FROM EMPANNUAL A 
LEFT OUTER JOIN EMPFAMILY_T B
ON A.EMPCD = B.EMPCD;

--RIGHT OUTER JOIN
SELECT * FROM STADIUM 
RIGHT OUTER JOIN TEAM
ON HOMETEAM_ID = TEAM_ID;

SELECT * FROM EMPANNUAL A 
RIGHT OUTER JOIN EMPFAMILY_T B
ON A.EMPCD = B.EMPCD;

--FULL OUTER JOIN
SELECT * FROM STADIUM FULL OUTER JOIN TEAM
ON HOMETEAM_ID = TEAM_ID;

SELECT * FROM EMPANNUAL A 
FULL OUTER JOIN EMPFAMILY_T B
ON A.EMPCD = B.EMPCD;

SELECT * FROM 
EMPANNUAL A 
,EMPFAMILY_T B
WHERE 
A.EMPCD = B.EMPCD(+);

--셀프조인(SELF JOIN)
SELECT E1.ENAME 사원, E2.ENAME 매니저 FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO;

SELECT A.BASICSTAX, B.RESIDENCETAX
FROM EMPTAX_T A
JOIN EMPTAX_T B 
ON A.BASICSTAX >= B.RESIDENCETAX;